-- Create "groups" table
CREATE TABLE "public"."groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "shops" table
CREATE TABLE "public"."shops" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("id")
);
-- Create "users" table
CREATE TABLE "public"."users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "age" bigint NOT NULL,
  "name" character varying NOT NULL DEFAULT 'unknown',
  PRIMARY KEY ("id")
);
-- Create "cars" table
CREATE TABLE "public"."cars" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "model" character varying NOT NULL,
  "registered_at" timestamptz NOT NULL,
  "user_cars" bigint NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "cars_users_cars" FOREIGN KEY ("user_cars") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
